# Generated by Django 5.2.4 on 2026-03-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('water_required_per_day', models.FloatField(help_text='Litres per day')),
                ('ideal_moisture', models.FloatField(help_text='Ideal soil moisture %')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('land_size', models.FloatField(help_text='Size of land in acres')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('rainfall_expected', models.BooleanField(default=False)),
                ('water_suggested', models.FloatField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automated', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmerprofile')),
            ],
        ),
    ]
