# Generated by Django 5.2.4 on 2026-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_farmerprofile_land_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='land_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
