# Generated by Django 5.2.4 on 2026-03-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_farmerprofile_land_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_water_liters', models.FloatField()),
                ('actual_water_liters', models.FloatField()),
                ('water_saved_liters', models.FloatField()),
                ('energy_consumed_kwh', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmerprofile')),
            ],
        ),
    ]
