# Generated by Django 5.2.4 on 2026-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_waterusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterusagelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waterusagelog',
            name='energy_consumed_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterusagelog',
            name='water_saved_liters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
