# Generated by Django 5.2.4 on 2026-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_waterusagelog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterusagelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
