# Generated by Django 5.2.4 on 2026-03-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_waterusagelog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterusagelog',
            old_name='date',
            new_name='created_at',
        ),
    ]
