# Generated by Django 5.2.4 on 2026-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_date_waterusagelog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(help_text='Name of the crop', max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='ideal_moisture',
            field=models.FloatField(default=0, help_text='Ideal soil moisture %'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='water_required_per_day',
            field=models.FloatField(default=0, help_text='Litres of water required per day'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='land_size',
            field=models.FloatField(help_text='Land size in acres'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(help_text="Farmer's location", max_length=100),
        ),
        migrations.AlterField(
            model_name='irrigationrecord',
            name='automated',
            field=models.BooleanField(default=True, help_text='Was irrigation automated?'),
        ),
        migrations.AlterField(
            model_name='irrigationrecord',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Irrigation recommendation'),
        ),
        migrations.AlterField(
            model_name='irrigationrecord',
            name='soil_moisture',
            field=models.FloatField(default=0, help_text='Current soil moisture %'),
        ),
        migrations.AlterField(
            model_name='irrigationrecord',
            name='temperature',
            field=models.FloatField(default=0, help_text='Temperature in °C'),
        ),
        migrations.AlterField(
            model_name='irrigationrecord',
            name='water_suggested',
            field=models.FloatField(default=0, help_text='AI suggested water in litres'),
        ),
        migrations.AlterField(
            model_name='waterusagelog',
            name='actual_water_liters',
            field=models.FloatField(default=0, help_text='Actual water used'),
        ),
        migrations.AlterField(
            model_name='waterusagelog',
            name='predicted_water_liters',
            field=models.FloatField(default=0, help_text='AI recommended water'),
        ),
    ]
